### PR TITLE
Parse Grafana notifications

### PR DESCRIPTION
**Pull request by svenseeberg**
Thanks for this neat project. I made some modifications to the code to support parsing [Grafana](https://github.com/grafana/grafana) notifications. I'm not really saying this needs to be merged, as this might totally be out of scope for this project. However, reading the interface from the environment and binding to localhost by default would be good, I think.

### CODE REVIEW

**Comment by nim65s** [comment]
Hi @svenseeberg,

Thanks for your interest, the practical use cases you bring to this project, and the example that fulfill your use case in the PR.

I can't merge this PR as it, because:
1. The `fork` notice in the README is a nice touch on your side, but can't be kept upstream ;)
2. The `parse_grafana_notification`function is way too specific for the scope of this project, and other uses it already have
3. This project started as a really simple, short and linear piece of code. Therefore, I was kind of able to justify my laziness and didn't add unit-test. But as soon as it gets more functionalities (eg. reading the key from multiple possible sources), I think we must add some.

On the other hand:
1. I think that providing multiple ways to specify the key is a really interesting feature. Many projects also put the shared secret in the HTTP headers, for instance. Others would by default send JWT.
2. Providing a template to format the message is also something that could become handy.
3. Thanks for adding the documentation for the forgotten `PORT` variable, and for fixing the `rel_url` → `path`! :D
4. I might also like to have Grafana notifications for myself…

I'll try to find a way to include all the good things you bring, while also fulfilling other similar use cases. 
And I'll add unit-tests.

**Comment by svenseeberg** [comment]
Thanks! I expected that. One other note: I'm running the script with a simple systemd unit file instead of a docker container. This works pretty well. Here's an example:

```
[Unit]
Description=Pipe webhook messages to Matrix

[Service]
ExecStart=/opt/matrix-webhook/.venv/bin/python3 /srv/matrix-webhook/matrix_webhook.py
User=matrix-webhook
Environment=MATRIX_URL="https://matrix.org"
Environment=MATRIX_ID="MYUSER"
Environment=MATRIX_PW="MYPASSWORD"
Environment=API_KEY="MYAPIKEY"
Environment=PORT="4785"
Environment=INTERFACE="127.0.0.1"

[Install]
WantedBy=multi-user.target
```

**Comment by nim65s** [comment]
Thanks for this other contribution :)

**Comment by svenseeberg** [comment]
Yes, that works :tada:

**Pull request closed without merging**
