### PR TITLE
join room before sending message

### PR DESCRIPTION
**Pull request by bboehmke**
With this change it will be checked if the room can be joined before sending the message.

### CODE REVIEW

**Comment by nim65s** [comment]
Nice feature, thanks :)

**Comment by nim65s** [comment]
I took the liberty of updating the unit test. Is this OK for you ?

**Comment by bboehmke** [comment]
sure! I have never done unit test for python so it would be much harder for me to fix this.

**Comment by nim65s** [comment]
ok !

**Pull request merged**
